added missing QVariant include
I ran into a compilation error because this include was missing:

client/src/audio/notification_sound_engine.h:46:9: error: return type ‘class QVariant’ is incomplete

This simple patch fixes it.